"""Firmware generation — turn the wired workbench into STM32 HAL firmware."""

from __future__ import annotations

from typing import Any

from schemas import (
    ComponentDefinition,
    FirmwareResult,
    GeneratedFile,
    WorkbenchState,
)

# STM32F103 GPIO pin labels -> (port, pin number).
GPIO_MAP: dict[str, tuple[str, int]] = {}
for _label in ["C13", "C14", "C15", "A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7",
                "B0", "B1", "B10", "B11", "B12", "B13", "B14", "B15", "A8", "A9",
                "A10", "A11", "A12", "A15", "B3", "B4", "B5", "B6", "B7", "B8", "B9"]:
    GPIO_MAP[_label] = (f"GPIO{_label[0]}", int(_label[1:]))

# Pins that can emit PWM via TIM2/TIM3 on the Blue Pill.
PWM_PINS = {"A0", "A1", "A2", "A3", "A6", "A7", "B0", "B1"}


def _pin_label(catalogue: dict[str, ComponentDefinition], component: dict[str, Any], pin_name: str) -> str:
    definition = catalogue.get(component.get("definition_id", ""))
    if not definition:
        return pin_name
    for pin in definition.pins:
        if pin.name == pin_name:
            return pin.label
    return pin_name


def generate_firmware(
    state: WorkbenchState, project_name: str, catalogue: dict[str, ComponentDefinition]
) -> FirmwareResult:
    """Turn the wired workbench into compilable STM32 HAL firmware."""
    placed = {item["id"]: item for item in state.placed_components}
    mcus = [item for item in state.placed_components
            if item.get("definition_id") == "stm32-blue-pill"]

    warnings: list[str] = []
    if not mcus:
        warnings.append("No STM32 board on the workbench - generated a bare skeleton.")
    if len(mcus) > 1:
        warnings.append("Multiple STM32 boards found - firmware targets the first one only.")

    mcu_id = mcus[0]["id"] if mcus else None

    outputs: list[tuple[str, str, str]] = []  # (gpio label, peripheral name, kind)
    seen_pins: set[str] = set()

    for wire in state.wires:
        endpoints = [wire.get("from", {}), wire.get("to", {})]
        mcu_endpoint = next((e for e in endpoints if e.get("componentId") == mcu_id), None)
        other = next((e for e in endpoints if e.get("componentId") != mcu_id), None)
        if not mcu_endpoint or not other:
            continue

        gpio_label = _pin_label(catalogue, placed.get(mcu_id, {}), mcu_endpoint.get("pinName", ""))
        if gpio_label not in GPIO_MAP:
            continue
        if gpio_label in seen_pins:
            continue
        seen_pins.add(gpio_label)

        peripheral = placed.get(other.get("componentId", ""), {})
        peripheral_def = catalogue.get(peripheral.get("definition_id", ""))
        peripheral_name = peripheral.get("display_name", "peripheral")
        kind = "gpio"
        if peripheral_def and peripheral_def.visual_type == "driver":
            kind = "pwm" if gpio_label in PWM_PINS else "gpio"
        elif peripheral_def and peripheral_def.visual_type == "led":
            kind = "gpio"
        outputs.append((gpio_label, peripheral_name, kind))

    summary = (
        f"{len(state.placed_components)} components, {len(state.wires)} wires, "
        f"{len(outputs)} driven GPIO line(s)."
    )

    gpio_header = """
#ifndef GPIO_H
#define GPIO_H

void gpio_init(void);

#endif
"""

    lines: list[str] = [
        f"/* Firmware for {project_name}",
        " * Auto-generated by HardcoreAI from the workbench netlist.",
        f" * {summary}",
        " */",
        '#include "stm32f1xx_hal.h"',
        "",
    ]

    if not outputs:
        warnings.append("No GPIO header pins are wired - loop body is empty.")

        return FirmwareResult(
            files=[
                GeneratedFile(
                    path="Core/Src/main.c",
                    language="c",
                    content="\n".join(lines) + "\n",
                )
            ],
            summary=summary,
            warnings=warnings,
        )

    gpio_lines = [
        '#include "gpio.h"',
        '#include "stm32f1xx_hal.h"',
        "",
        "void gpio_init(void) {",
        "    GPIO_InitTypeDef cfg = {0};",
        "    __HAL_RCC_GPIOA_CLK_ENABLE();",
        "    __HAL_RCC_GPIOB_CLK_ENABLE();",
        "    __HAL_RCC_GPIOC_CLK_ENABLE();",
        "",
        "    cfg.Mode = GPIO_MODE_OUTPUT_PP;",
        "    cfg.Pull = GPIO_NOPULL;",
        "    cfg.Speed = GPIO_SPEED_FREQ_LOW;",
        "",
    ]

    for gpio_label, peripheral_name, _kind in outputs:
        port, number = GPIO_MAP[gpio_label]
        gpio_lines.append(f"    /* {gpio_label} -> {peripheral_name} */")
        gpio_lines.append(f"    cfg.Pin = GPIO_PIN_{number};")
        gpio_lines.append(f"    HAL_GPIO_Init({port}, &cfg);")

    gpio_lines.append("}")

    main_lines = [
    f"/* Firmware for {project_name}",
    " * Auto-generated by HardcoreAI from the workbench netlist.",
    f" * {summary}",
    " */",
    '#include "stm32f1xx_hal.h"',
    '#include "gpio.h"',
    "",
    "int main(void) {",
    "    HAL_Init();",
    "    gpio_init();",
    "",
    "    while (1) {",
]
    for gpio_label, peripheral_name, _kind in outputs:
        port, number = GPIO_MAP[gpio_label]

        main_lines.append(
            f"        /* toggle {peripheral_name} */"
        )

        main_lines.append(
            f"        HAL_GPIO_TogglePin({port}, GPIO_PIN_{number});"
        )

    main_lines += [
        "        HAL_Delay(500);",
        "    }",
        "}",
    ]

    pwm_lines = [o for o in outputs if o[2] == "pwm"]
    if pwm_lines:
        warnings.append(
            f"{len(pwm_lines)} pin(s) wired to a driver support hardware PWM - "
            "currently emitted as plain toggle. Configure TIM2/TIM3 for speed control."
        )

    return FirmwareResult(
    files=[
        GeneratedFile(
            path="Core/Src/main.c",
            language="c",
            content="\n".join(main_lines) + "\n",
        ),
        GeneratedFile(
            path="Core/Src/gpio.c",
            language="c",
            content="\n".join(gpio_lines) + "\n",
        ),
        GeneratedFile(
            path="Core/Inc/gpio.h",
            language="c",
            content=gpio_header,
        ),
    ],
    summary=summary,
    warnings=warnings,
)
