# hal_codegen.py
# Pure function — takes board + peripherals, returns dict of {filepath: content}
# No file I/O here. The route handler (hal_generate.py) does the actual writing.

from __future__ import annotations
import textwrap
from typing import Any

BOARD_META = {
    "STM32F401": {
        "mcu": "STM32F401RETx",
        "hal_header": "stm32f4xx_hal.h",
        "core_clock": "84000000UL",
    },
    "STM32F103": {
        "mcu": "STM32F103C8Tx",
        "hal_header": "stm32f1xx_hal.h",
        "core_clock": "72000000UL",
    },
    "STM32H743": {
        "mcu": "STM32H743ZITx",
        "hal_header": "stm32h7xx_hal.h",
        "core_clock": "480000000UL",
    },
}

_DEFAULT_META = {
    "mcu": "STM32F401RETx",
    "hal_header": "stm32f4xx_hal.h",
    "core_clock": "84000000UL",
}

# Templates for each peripheral.
# {mcu}, {hal_header}, {core_clock}, {mode} get substituted in.
TEMPLATES: dict[str, dict[str, str]] = {
    "rcc": {
        "src/hal/rcc_init.c": textwrap.dedent("""\
            /* rcc_init.c — generated by HardcoreAI for {mcu} */
            #include "{hal_header}"

            void SystemClock_Config(void) {{
                RCC_OscInitTypeDef osc = {{0}};
                RCC_ClkInitTypeDef clk = {{0}};

                /* {mode} */
                osc.OscillatorType = RCC_OSCILLATORTYPE_HSE;
                osc.HSEState       = RCC_HSE_ON;
                osc.PLL.PLLState   = RCC_PLL_ON;
                osc.PLL.PLLSource  = RCC_PLLSOURCE_HSE;
                osc.PLL.PLLM       = 8;
                osc.PLL.PLLN       = 336;
                osc.PLL.PLLP       = RCC_PLLP_DIV4;
                osc.PLL.PLLQ       = 7;
                HAL_RCC_OscConfig(&osc);

                clk.ClockType      = RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_HCLK
                                   | RCC_CLOCKTYPE_PCLK1  | RCC_CLOCKTYPE_PCLK2;
                clk.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
                clk.AHBCLKDivider  = RCC_SYSCLK_DIV1;
                clk.APB1CLKDivider = RCC_HCLK_DIV2;
                clk.APB2CLKDivider = RCC_HCLK_DIV1;
                HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_2);
            }}
        """),
        "src/hal/rcc_init.h": textwrap.dedent("""\
            /* rcc_init.h — generated by HardcoreAI for {mcu} */
            #pragma once
            void SystemClock_Config(void);
        """),
    },

    "gpio": {
        "src/hal/gpio_init.c": textwrap.dedent("""\
            /* gpio_init.c — generated by HardcoreAI for {mcu} */
            #include "{hal_header}"

            void MX_GPIO_Init(void) {{
                GPIO_InitTypeDef gpio = {{0}};

                __HAL_RCC_GPIOA_CLK_ENABLE();
                __HAL_RCC_GPIOB_CLK_ENABLE();
                __HAL_RCC_GPIOC_CLK_ENABLE();

                /* PA5 — onboard LED ({mode}) */
                gpio.Pin   = GPIO_PIN_5;
                gpio.Mode  = GPIO_MODE_OUTPUT_PP;
                gpio.Pull  = GPIO_NOPULL;
                gpio.Speed = GPIO_SPEED_FREQ_LOW;
                HAL_GPIO_Init(GPIOA, &gpio);
            }}
        """),
        "src/hal/gpio_init.h": textwrap.dedent("""\
            /* gpio_init.h — generated by HardcoreAI for {mcu} */
            #pragma once
            void MX_GPIO_Init(void);
        """),
    },

    "usart1": {
        "src/hal/uart1_init.c": textwrap.dedent("""\
            /* uart1_init.c — generated by HardcoreAI for {mcu} */
            #include "{hal_header}"

            UART_HandleTypeDef huart1;

            void MX_USART1_UART_Init(void) {{
                huart1.Instance          = USART1;
                huart1.Init.BaudRate     = 115200;
                huart1.Init.WordLength   = UART_WORDLENGTH_8B;
                huart1.Init.StopBits     = UART_STOPBITS_1;
                huart1.Init.Parity       = UART_PARITY_NONE;
                huart1.Init.Mode         = UART_MODE_TX_RX; /* {mode} */
                huart1.Init.HwFlowCtl   = UART_HWCONTROL_NONE;
                huart1.Init.OverSampling = UART_OVERSAMPLING_16;
                HAL_UART_Init(&huart1);
            }}
        """),
        "src/hal/uart1_init.h": textwrap.dedent("""\
            /* uart1_init.h — generated by HardcoreAI for {mcu} */
            #pragma once
            #include "{hal_header}"
            extern UART_HandleTypeDef huart1;
            void MX_USART1_UART_Init(void);
        """),
    },

    "usart2": {
        "src/hal/uart2_init.c": textwrap.dedent("""\
            /* uart2_init.c — generated by HardcoreAI for {mcu} */
            #include "{hal_header}"

            UART_HandleTypeDef huart2;

            void MX_USART2_UART_Init(void) {{
                huart2.Instance          = USART2;
                huart2.Init.BaudRate     = 115200;
                huart2.Init.WordLength   = UART_WORDLENGTH_8B;
                huart2.Init.StopBits     = UART_STOPBITS_1;
                huart2.Init.Parity       = UART_PARITY_NONE;
                huart2.Init.Mode         = UART_MODE_TX_RX; /* {mode} */
                huart2.Init.HwFlowCtl   = UART_HWCONTROL_NONE;
                huart2.Init.OverSampling = UART_OVERSAMPLING_16;
                HAL_UART_Init(&huart2);
            }}
        """),
        "src/hal/uart2_init.h": textwrap.dedent("""\
            /* uart2_init.h — generated by HardcoreAI for {mcu} */
            #pragma once
            #include "{hal_header}"
            extern UART_HandleTypeDef huart2;
            void MX_USART2_UART_Init(void);
        """),
    },

    "spi1": {
        "src/hal/spi1_init.c": textwrap.dedent("""\
            /* spi1_init.c — generated by HardcoreAI for {mcu} */
            #include "{hal_header}"

            SPI_HandleTypeDef hspi1;

            void MX_SPI1_Init(void) {{
                hspi1.Instance               = SPI1;
                hspi1.Init.Mode              = SPI_MODE_MASTER; /* {mode} */
                hspi1.Init.Direction         = SPI_DIRECTION_2LINES;
                hspi1.Init.DataSize          = SPI_DATASIZE_8BIT;
                hspi1.Init.CLKPolarity       = SPI_POLARITY_LOW;
                hspi1.Init.CLKPhase          = SPI_PHASE_1EDGE;
                hspi1.Init.NSS               = SPI_NSS_SOFT;
                hspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_8;
                hspi1.Init.FirstBit          = SPI_FIRSTBIT_MSB;
                hspi1.Init.TIMode            = SPI_TIMODE_DISABLE;
                hspi1.Init.CRCCalculation    = SPI_CRCCALCULATION_DISABLE;
                HAL_SPI_Init(&hspi1);
            }}
        """),
        "src/hal/spi1_init.h": textwrap.dedent("""\
            /* spi1_init.h — generated by HardcoreAI for {mcu} */
            #pragma once
            #include "{hal_header}"
            extern SPI_HandleTypeDef hspi1;
            void MX_SPI1_Init(void);
        """),
    },

    "i2c1": {
        "src/hal/i2c1_init.c": textwrap.dedent("""\
            /* i2c1_init.c — generated by HardcoreAI for {mcu} */
            #include "{hal_header}"

            I2C_HandleTypeDef hi2c1;

            void MX_I2C1_Init(void) {{
                hi2c1.Instance             = I2C1;
                hi2c1.Init.ClockSpeed      = 100000; /* {mode} */
                hi2c1.Init.DutyCycle       = I2C_DUTYCYCLE_2;
                hi2c1.Init.OwnAddress1     = 0;
                hi2c1.Init.AddressingMode  = I2C_ADDRESSINGMODE_7BIT;
                hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
                hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
                hi2c1.Init.NoStretchMode   = I2C_NOSTRETCH_DISABLE;
                HAL_I2C_Init(&hi2c1);
            }}
        """),
        "src/hal/i2c1_init.h": textwrap.dedent("""\
            /* i2c1_init.h — generated by HardcoreAI for {mcu} */
            #pragma once
            #include "{hal_header}"
            extern I2C_HandleTypeDef hi2c1;
            void MX_I2C1_Init(void);
        """),
    },

    "tim1": {
        "src/hal/tim1_init.c": textwrap.dedent("""\
            /* tim1_init.c — generated by HardcoreAI for {mcu} */
            #include "{hal_header}"

            TIM_HandleTypeDef htim1;

            void MX_TIM1_Init(void) {{
                TIM_OC_InitTypeDef oc = {{0}};
                htim1.Instance               = TIM1;
                htim1.Init.Prescaler         = ({core_clock} / 1000000UL) - 1;
                htim1.Init.CounterMode       = TIM_COUNTERMODE_UP;
                htim1.Init.Period            = 999; /* {mode} */
                htim1.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
                htim1.Init.RepetitionCounter = 0;
                htim1.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_ENABLE;
                HAL_TIM_PWM_Init(&htim1);
                oc.OCMode     = TIM_OCMODE_PWM1;
                oc.Pulse      = 500;
                oc.OCPolarity = TIM_OCPOLARITY_HIGH;
                HAL_TIM_PWM_ConfigChannel(&htim1, &oc, TIM_CHANNEL_1);
            }}
        """),
        "src/hal/tim1_init.h": textwrap.dedent("""\
            /* tim1_init.h — generated by HardcoreAI for {mcu} */
            #pragma once
            #include "{hal_header}"
            extern TIM_HandleTypeDef htim1;
            void MX_TIM1_Init(void);
        """),
    },

    "adc1": {
        "src/hal/adc1_init.c": textwrap.dedent("""\
            /* adc1_init.c — generated by HardcoreAI for {mcu} */
            #include "{hal_header}"

            ADC_HandleTypeDef hadc1;

            void MX_ADC1_Init(void) {{
                ADC_ChannelConfTypeDef ch = {{0}};
                hadc1.Instance                  = ADC1;
                hadc1.Init.ClockPrescaler        = ADC_CLOCK_SYNC_PCLK_DIV4;
                hadc1.Init.Resolution            = ADC_RESOLUTION_12B; /* {mode} */
                hadc1.Init.ScanConvMode          = DISABLE;
                hadc1.Init.ContinuousConvMode    = DISABLE;
                hadc1.Init.ExternalTrigConvEdge  = ADC_EXTERNALTRIGCONVEDGE_NONE;
                hadc1.Init.ExternalTrigConv      = ADC_SOFTWARE_START;
                hadc1.Init.DataAlign             = ADC_DATAALIGN_RIGHT;
                hadc1.Init.NbrOfConversion       = 1;
                HAL_ADC_Init(&hadc1);
                ch.Channel      = ADC_CHANNEL_0;
                ch.Rank         = 1;
                ch.SamplingTime = ADC_SAMPLETIME_3CYCLES;
                HAL_ADC_ConfigChannel(&hadc1, &ch);
            }}
        """),
        "src/hal/adc1_init.h": textwrap.dedent("""\
            /* adc1_init.h — generated by HardcoreAI for {mcu} */
            #pragma once
            #include "{hal_header}"
            extern ADC_HandleTypeDef hadc1;
            void MX_ADC1_Init(void);
        """),
    },

    "dma": {
        "src/hal/dma_init.c": textwrap.dedent("""\
            /* dma_init.c — generated by HardcoreAI for {mcu} */
            #include "{hal_header}"

            void MX_DMA_Init(void) {{
                __HAL_RCC_DMA1_CLK_ENABLE();
                __HAL_RCC_DMA2_CLK_ENABLE();
                HAL_NVIC_SetPriority(DMA1_Stream0_IRQn, 0, 0);
                HAL_NVIC_EnableIRQ(DMA1_Stream0_IRQn);
            }}
        """),
        "src/hal/dma_init.h": textwrap.dedent("""\
            /* dma_init.h — generated by HardcoreAI for {mcu} */
            #pragma once
            void MX_DMA_Init(void);
        """),
    },

    "nvic": {
        "src/hal/nvic_init.c": textwrap.dedent("""\
            /* nvic_init.c — generated by HardcoreAI for {mcu} */
            #include "{hal_header}"

            void MX_NVIC_Init(void) {{
                HAL_NVIC_SetPriorityGrouping(NVIC_PRIORITYGROUP_4);
            }}
        """),
        "src/hal/nvic_init.h": textwrap.dedent("""\
            /* nvic_init.h — generated by HardcoreAI for {mcu} */
            #pragma once
            void MX_NVIC_Init(void);
        """),
    },
}

# Maps peripheral id → the init call string for main_init.c
INIT_CALLS = {
    "rcc":    "    SystemClock_Config();",
    "gpio":   "    MX_GPIO_Init();",
    "dma":    "    MX_DMA_Init();",
    "nvic":   "    MX_NVIC_Init();",
    "usart1": "    MX_USART1_UART_Init();",
    "usart2": "    MX_USART2_UART_Init();",
    "spi1":   "    MX_SPI1_Init();",
    "i2c1":   "    MX_I2C1_Init();",
    "tim1":   "    MX_TIM1_Init();",
    "adc1":   "    MX_ADC1_Init();",
}

INCLUDES = {
    "rcc": '#include "hal/rcc_init.h"',
    "gpio": '#include "hal/gpio_init.h"',
    "dma": '#include "hal/dma_init.h"',
    "nvic": '#include "hal/nvic_init.h"',
    "usart1": '#include "hal/uart1_init.h"',
    "usart2": '#include "hal/uart2_init.h"',
    "spi1": '#include "hal/spi1_init.h"',
    "i2c1": '#include "hal/i2c1_init.h"',
    "tim1": '#include "hal/tim1_init.h"',
    "adc1": '#include "hal/adc1_init.h"',
}

def generate_hal_files(board: str, peripherals: list[dict[str, Any]]) -> dict[str, str]:
    """
    Returns a dict of { "src/hal/filename.c": "file content string" }
    for every enabled peripheral + a main_init.c orchestrator.
    """
    meta = {**_DEFAULT_META, **BOARD_META.get(board, {})}
    files: dict[str, str] = {}

    # DMA first if present (must init before other peripherals use it)
    ordered = sorted(peripherals, key=lambda p: 0 if p["id"] == "dma" else 1)

    init_calls: list[str] = []
    includes: list[str] = []

    for p in ordered:
        pid = p["id"]
        if pid not in TEMPLATES:
            continue  # unknown peripheral — silently skip

        fmt = {**meta, "mode": p.get("mode", "")}
        for rel_path, template in TEMPLATES[pid].items():
            files[rel_path] = template.format_map(fmt)

        if pid in INIT_CALLS:
            init_calls.append(INIT_CALLS[pid])
            includes.append(INCLUDES[pid])

    # Generate the top-level orchestrator that calls everything
    peripheral_names = ", ".join(p["id"].upper() for p in peripherals)
    files["src/hal/main_init.c"] = (
        f"/* main_init.c — generated by HardcoreAI for {meta['mcu']} */\n"
        f"/* Board: {board}  |  Peripherals: {peripheral_names} */\n"
        f'#include "{meta["hal_header"]}"\n'
        + "\n".join(includes) + "\n\n"
        "void HAL_Init_All(void) {\n"
        "    HAL_Init();\n"
        + "\n".join(init_calls) + "\n"
        "}\n"
    )
    files["src/hal/main_init.h"] = (
        f"/* main_init.h — generated by HardcoreAI for {meta['mcu']} */\n"
        "#pragma once\n"
        "void HAL_Init_All(void);\n"
    )

    return files